### PR TITLE
Added Princeton

### PR DESCRIPTION
**Pull request by dhruvapte26**

### CODE REVIEW

**Comment by athityakumar** [comment]
@the-ethan-hunt - This is certainly a good start. Can you also include the princeton.csv file generated by this ruby script?

**Comment by dhruvapte26** [comment]
Hi, I repaired the Princeton code and also added the file for UCLA. But still, no .csv files created

**Comment by athityakumar** [comment]
@the-ethan-hunt : The link you were using for princeton.rb was throwing a 404 Error. So, I've removed that file & also changed ucla.rb to make it work. Do delete your fork & re-fork my repo again. :smile:

**Comment by dhruvapte26** [comment]
Ok. Thanks for your help! :+1:

**Pull request closed without merging**
