### PR TITLE
Added CS faculty of UIUC

### PR DESCRIPTION
**Pull request by sgdgp**

### CODE REVIEW

**Comment by athityakumar** [comment]
@sgdgp - Great start, Sayan. Keep the contributions coming in.

Just a very minor change I'd like to suggest, to keep the ruby scripts consistent - can you remove the unnecessary empty lines in `uiuc.rb`?

**Comment by sgdgp** [comment]
Ok, Will keep your advice in mind and make scripts consistent.
Thanks



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sgdgp.2014@gmail.com&idSignature=22>

**Comment by sgdgp** [comment]
Is the file ok now ?

**Comment by athityakumar** [comment]
@sgdgp : Yep, I'm merging this now. Keep up the good work. :smile:

**Pull request merged**
